import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-600">HOLA</h1>
    </div>
  );
}
